select
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
from ONLINE_SALE
where SALES_DATE >= '2022-03-01' and SALES_DATE < '2022-04-01'

UNION ALL

select
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d')AS SALES_DATE,
    PRODUCT_ID,
    NULL AS USER_ID,        
    SALES_AMOUNT
from OFFLINE_SALE
where SALES_DATE >= '2022-03-01' and SALES_DATE < '2022-04-01'

order by SALES_DATE, PRODUCT_ID, USER_ID