-- 코드를 입력하세요
SELECT 
    CAR_ID,
    round(AVG(END_DATE-START_DATE),1) AS AVERAGE_DURATION
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
group by CAR_ID
having AVG(END_DATE-START_DATE)>=7
order by AVERAGE_DURATION DESC, CAR_ID DESC
